### Numpy basics

In [3]:
import numpy as np

1\. Find the row, column and overall means for the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [20]:
m = np.arange(12).reshape((3,4))
print(f"Respectively, rows and columns: {m.shape[0]}, {m.shape[1]}")
print(f"Rank: {m.ndim}")

Respectively, rows and columns: 3, 4
Rank: 2


2\. Find the outer product of the following two vecotrs

```python
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
```

Do this in the following ways:

   * Using the function outer in numpy
   * Using a nested for loop or list comprehension
   * Using numpy broadcasting operatoins


In [28]:
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])

# Using the function outer
print(np.outer(u, v), "\n")

# List comprehension, N.B. this works only for 1D vectors
prod = [int(i*j) for i in u for j in v]
prod = np.array(prod).reshape(u.shape[0], v.shape[0])
print(prod, "\n")

# Broadcasting operations
print(u[:, None] * v[None, :])

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero

Hint: Use the following numpy functions - np.random.random, np.any as well as Boolean indexing and the axis argument.

In [46]:
uniform = np.random.random((10, 6))
print("Before applying the function: \n", uniform, "\n")

# Find the rows
rows = []
for i in range(10):
    for j in range(6):
        if np.any(uniform[i][j] < 0.1, axis = 0):
            rows.append(i)

# Set all elements to zero
for row in rows:
    for j in range(6):
        uniform[row][j] = 0

print(f"After applying the function: \n {uniform}")

Before applying the function: 
 [[0.27658008 0.92840115 0.76029752 0.61671375 0.31808393 0.38146916]
 [0.25231357 0.88444096 0.08351961 0.92452334 0.76309505 0.50853916]
 [0.28006583 0.32703634 0.27019862 0.08079807 0.78178022 0.12514777]
 [0.93041453 0.06770765 0.17263523 0.7980617  0.8905226  0.42383107]
 [0.82110813 0.28638408 0.91288664 0.06856583 0.20087388 0.37026509]
 [0.03531826 0.78155733 0.36942162 0.8009941  0.85463989 0.14169057]
 [0.79939119 0.39399818 0.57853816 0.1646043  0.33460998 0.03710142]
 [0.90929712 0.15018132 0.26121426 0.2110075  0.36139052 0.74370535]
 [0.65955124 0.37333927 0.05016163 0.48747796 0.45443502 0.80750013]
 [0.41593773 0.05094256 0.51303717 0.82633388 0.2621338  0.487272  ]] 

After applying the function: 
 [[0.27658008 0.92840115 0.76029752 0.61671375 0.31808393 0.38146916]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.

4\. Use np.linspace to create an array of 100 numbers between 0 and 2π (inclusive).

  * Extract every 10th element using slice notation
  * Reverse the array using slice notation
  * Extract elements where the absolute difference between the sine and cosine functions evaluated at that element is less than 0.1
  * Make a plot showing the sin and cos functions and indicate where they are close

In [98]:
import matplotlib.pyplot as plt

lin = np.linspace(0, 2*np.pi, 100)
tens = lin[::10]
reverse = lin[::-1]
diff = [float(i) for i in lin if (np.sin(i)-np.cos(i)) < 0.1]

plt.plot(lin, np.sin(lin), label="sin")
plt.plot(lin, np.cos(lin), label="cos")
plt.legend()

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anto-diagonal (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagnoal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [82]:
a = np.arange(1,11)
mult_table = np.outer(a,a)
print(mult_table)

# Trace
trace = 0
for i, j in zip(range(10), range(10)):
    trace += mult_table[i][j]
print(trace)

# Anto-diagonal (9,0), (8,1) ecc
rows_anto = np.arange(10)
col_anto = 9 - rows_anto
anto_diagonal = np.zeros(10)
for i, j in zip(rows_anto, col_anto):
    anto_diagonal[i] = mult_table[i][j]
print(anto_diagonal)

# Diagonal offset
rows_diag = np.arange(9)
col_diag = 1 + rows_diag
diag_offset = np.zeros(9)
for i, j in zip(rows_diag, col_diag):
    diag_offset[i] = mult_table[i][j]
print(diag_offset)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
385
[10. 18. 24. 28. 30. 30. 28. 24. 18. 10.]
[ 2.  6. 12. 20. 30. 42. 56. 72. 90.]


6\. Use broadcasting to create a grid of distances

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Construct a 2D grid of distances among each city along Route 66
  * Convert that in km (those savages...)

In [92]:
pos = np.array([0,198,303,736,871,1175,1475,1544,1913,2448])

# Miles
distances = np.abs(pos[:, None] - pos[None, :])

# Km (1 mile is approx 1.6km)
distances_km = distances / 1.6

7\. Prime numbers sieve: compute the prime numbers in the 0-N (N=99 to start with) range with a sieve (mask).
  * Constract a shape (100,) boolean array, the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [105]:
# Array of numbers where to apply the mask
N = 10000000      # To be eventually changed
n = np.arange(N+1)

# Actual mask
mask = np.ones(N+1, dtype=bool)   # Every number is considered prime at the beginning
mask[0:2] = False                 # 0 and 1 aren't primes, so we exclude the,
for i in np.arange(2, N+1):
    if mask[i]:
        mask[2*i : N+1 : i] = False

# Application without Eratosthenes sieve
primes = n[mask]
print(primes)

%timeit n[mask]

[      2       3       5 ... 9999971 9999973 9999991]
49.8 ms ± 1.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [104]:
# Array of numbers where to apply the mask
N = 10000000                   # To be eventually changed
n = np.arange(N+1)    

# Actual mask
mask = np.ones(N+1, dtype=bool)   # Every number is considered prime at the beginning
mask[0:2] = False
for i in np.arange(2, int(np.sqrt(N))+1):
    if mask[i]:
        mask[i*i : N+1 : i] = False

# Erathostenes sieve
primes_er = n[mask]
print(primes_er)

%timeit n[mask]

[    2     3     5 ... 19991 19993 19997]
125 μs ± 3.18 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


**N.B. the following exercises are meant to be solved only if you are familiar with the numpy random library. If not you can skip them (postponed for one of the next exercise sessions)**


8\. Diffusion using random walk

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of a random walker after a given amount of time. 
To do that, let's simulate many walkers and create a 2D array with each walker as a raw and the actual time evolution as columns

  * Take 1000 walkers and let them walk for 200 steps
  * Use randint to create a 2D array of size walkers x steps with values -1 or 1
  * Build the actual walking distances for each walker (i.e. another 2D array "summing on each raw")
  * Take the square of that 2D array (elementwise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * Plot the average distances (sqrt(distance\*\*2)) as a function of time (step)
  
Did you get what you expected?

9\. Analyze a data file 
  * Download the population of hares, lynxes and carrots at the beginning of the last century.
    ```python
    ! wget https://www.dropbox.com/s/3vigxoqayo389uc/populations.txt
    ```

  * Check the content by looking within the file
  * Load the data (use an appropriate numpy method) into a 2D array
  * Create arrays out of the columns, the arrays being (in order): *year*, *hares*, *lynxes*, *carrots* 
  * Plot the 3 populations over the years
  * Compute the main statistical properties of the dataset (mean, std, correlations, etc.)
  * Which species has the highest population each year?

Do you feel there is some evident correlation here? [Studies](https://www.enr.gov.nt.ca/en/services/lynx/lynx-snowshoe-hare-cycle) tend to believe so.